export enum HTTPStatus {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  NOT_MODIFIED = 304,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  UNPROCESSABLE_ENTITY = 422,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
}

export type HTTPErrorStatus =
  | HTTPStatus.BAD_REQUEST
  | HTTPStatus.UNAUTHORIZED
  | HTTPStatus.PAYMENT_REQUIRED
  | HTTPStatus.FORBIDDEN
  | HTTPStatus.NOT_FOUND
  | HTTPStatus.CONFLICT
  | HTTPStatus.UNPROCESSABLE_ENTITY
  | HTTPStatus.TOO_MANY_REQUESTS
  | HTTPStatus.INTERNAL_SERVER_ERROR
  | HTTPStatus.NOT_IMPLEMENTED
  | HTTPStatus.BAD_GATEWAY;

export type HTTPSuccessStatus = Exclude<HTTPStatus, HTTPErrorStatus>;
